### ISSUE TITLE
unproved VC with only one quantifier instance needed

### ISSUE THREAD

**Issue by clairedross** [CVC4/CVC4#3481]
Hi CVC4 team,
while working on some SPARK code, I have encountered a VC which seemed provable to me but for which cvc4 1.7.1 (and I think cvc4 master too) returns unknown almost instantly. The VC attached may look a bit complicated because it is generated code, but really, only the last 2 asserts are of interest. The first one is a universally quantified formula, and the other is the negation of an instance of this formula (if I have not done any mistake). I would be interested in understanding what is causing the issue for CVC4, and if there would be a (systematic) way to help the prover here.
Best regards,
Claire
[cvc4_unproved.txt](https://github.com/CVC4/CVC4/files/3869738/cvc4_unproved.txt)

**Comment by ajreynol** [comment]
Thanks for the benchmark.

This benchmark is no longer solved after the change to its heuristics that enabled CVC4 to solve the benchmark from #993. 

In particular, this benchmark can be solved by CVC4 by `--quant-dsplit=none`, while enabling this option makes the benchmark from #993 fail.

I will look into how to get CVC4 to solve both these benchmarks.

**Comment by clairedross** [comment]
Thanks a lot for your quick answer. I know that heuristics for quantifier instantiations are tricky. Is the problem caused by interactions between quantifier handling and theory reasonning?

**Comment by ajreynol** [comment]
It's hard to tell. The heuristic in question is whether to "split" quantified formulas based on variables of datatype type, where that datatype has a single constructor. There are cases where this helps and does not.  I've updated the policy on this heuristic in my latest commit so that we can reason about *both* the split/non-split version of the quantified formula.  This seems to be the best alternative for unsat queries.  Notice that now both benchmarks, the one in this issue and the one in #993, are solved using `--full-saturate-quant` (which I assume you are using by default?).

**Comment by clairedross** [comment]
I don't think we are currently using this switch by default. We have: -no-bv-div-zero-const --no-cond-rewrite-quant --bitblast-step=5 --cnf-step=5 --lemma-step=5 --parse-step=0 --preprocess-step=0 --restart-step=10 --rewrite-step=0
I think we tried this switch in the past, and the results were inconclusive. I will try it again.
Thanks,

**Comment by clairedross** [comment]
Hi Andrew,
we have tested this switch again, and it seems we cannot use it, as it degrades performances too much on most of our tests. Do you think there could be a way to write our quantifiers to avoid the need for this option and still get the necessary instance?
BTW, I didn't manage to reopen the issue. Should I create a new one?
Thanks in advance,
Best,
Claire

**Comment by ajreynol** [comment]
Hi Claire, that's a bit unfortunate.  I'll reopen this issue and look into it again.

**Comment by ajreynol** [comment]
Btw, to confim, the switch you mention is `--full-saturate-quant` right?

As I may have mentioned, this option will have the effect of turning some "unknown" into "unsat" and some "unknown" into timeouts.  It should (almost) never make a benchmark go "unsat" -> unsolved.  I assume your degradation in performance is because you would prefer "unknown" to timeouts?

**Comment by kanigsson** [comment]
From what I gather, indeed the biggest performance hit comes from "unknown" VCs where cvc4, instead of returning unknown almost immediately, runs for the full provided time limit (I tried with 10 seconds). It's not strictly a regression but it does result in longer running times.
I picked ~200 VCs at random from our bench, and 2 of them go from "unsat" to "unknown", again with a timeout of 10 seconds, and again cvc4 taking the full time, so it looks like this actually happens in our VCs. Let me know if you want to see any of the files in question.

**Comment by ajreynol** [comment]
To clarify here, you have 2 benchmarks that default answers "unsat" (solved in 10 seconds) and `--full-saturate-quant` answers "unknown" (timeout in 10 seconds)?  I would be interested in seeing these 2 VCs.  I

**Comment by ajreynol** [comment]
Also, I did run a sanity check on all of SMT-LIB quantified logics with UF timeout 30 seconds.

Out of ~23k benchmarks, there were only 2 benchmarks that went unsat (default, without `--full-saturate-quant`) -> timeout (with `--full-saturate-quant`) that were both on the borderline of timeout (>29 seconds).  Moreover there was only 5 benchmarks that solved >1 second faster with default vs. `--full-saturate-quant` (again this should be noise).  This means that the only negative effect of `--full-saturate-quant` should just be the issue of "unknown" -> timeout issue.  

Btw, what command line options are you using otherwise?

**Comment by ajreynol** [comment]
My PR on #3760 makes it so that you can compromise how many rounds of `--full-saturate-quant` you want to run with `--full-saturate-quant-limit=N`, where N>=2 solves the benchmark from this issue. 

My hope is that a small N (say around 3-5) should give you the benefits of more unsat without too many "unknown" -> timeouts.

**Comment by kanigsson** [comment]
I have added the two files "unsat -> timeout" to this comment. In this bench I didn't add any other commandline options, just `--statistics` and `--quiet`. Note that these were found by picking 200 VCs at random from our bench, I would expect many more like that. Also among these 200 there are quite a few (maybe 10?) unknown (finishing in a fraction of a second) that become timeout (taking the full timeout).

Note that our bench is 

[unsat2.smt2.txt](https://github.com/CVC4/CVC4/files/4216711/unsat2.smt2.txt)
[unsat1.smt2.txt](https://github.com/CVC4/CVC4/files/4216710/unsat1.smt2.txt)

I will play with your option `--full-saturate-quant-limit`, thank you very much! BTW, is that in addition to or in place of `--full-saturate-quant`?

**Comment by kanigsson** [comment]
FYI I have put our full bench in a github repo: https://github.com/kanigsson/spark2014bench Note that it doesn't contain oracles, and many VCs are in fact unprovable (so the bench can't be 100% proved).

**Comment by ajreynol** [comment]
Thanks for the benchmarks, indeed I see that `--full-saturate-quant` kicks in too eagerly for these cases.  I have a branch that resolves this issue so that `--full-saturate-quant` solves both of the above.  But regardless I think that playing around with `--full-saturate-quant-limit` is the option you need at the moment.

**Comment by ajreynol** [comment]
Also, would it be okay to include the benchmark set from the above repository in SMT-LIB?  This would ensure that these benchmarks are run in my tests more consistently.

**Comment by kanigsson** [comment]
This benchmark set is fully public. Let me know if there is anything we can do to make it easier for you to use these benchmarks.

**Comment by ajreynol** [comment]
FYI, CVC4 with `--full-saturate-quant` alone is +125-3 (125 new solves to 3 lost) with a 60 second timeout on your benchmark suite after #3744, although again the unknown->timeout issue remains as expected.

Do let me know if `--full-saturate-quant-limit=N` works for you.

**Comment by ajreynol** [comment]
Hi @kanigsson , would it be possible for you to submit the benchmarks from your repository as pending benchmarks to SMT-LIB?  There are instructions here: https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks-tmp/benchmarks-pending/tree/master

In particular, you would need to add a standard header to the benchmarks:
```
(set-info :smt-lib-version <version>)
(set-logic <logic>)
(set-info :source |<description>|)
(set-info :license "https://creativecommons.org/licenses/by/4.0/")
(set-info :category <category>)
(set-info :status <status>)
```

This would be great if we could include these in SMT-LIB, let me know if I can help with this.

**Comment by kanigsson** [comment]
Yes that would be great! I have some questions about this, but I will ask a maintainer. As for the discussion on this ticket, I haven't had time yet to check the impact of `--full-saturate-quant-limit`, but I will definitely come back to this soon.
